CREATE TABLE [MaskUnMask].[Application](
	[ApplicationId] INT  NOT NULL PRIMARY KEY IDENTITY(1,1),
	[ApplicationName] VARCHAR(50) NOT NULL,
	[Description] VARCHAR(50) NULL,
	[IsActive] BIT NOT NULL DEFAULT 1,
	[IsDeleted] BIT NOT NULL DEFAULT 0,
	[CreatedDate] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME ( ) ,
	[CreatedBy] VARCHAR(50) NOT NULL DEFAULT 'System',
	[ModifiedDate] DATETIME2 NULL,
	[ModifiedBy] DATETIME2 NULL
	)